<?php

// Generated by Transtable - 2015-04-25 17:53:18

$t['navBrandMain'] = 'Hallym University';
$t['navBrandSub'] = 'College of International Studies';
$t['navAbout'] = 'About CIS';
$t['navAboutFaculty'] = 'Faculty';
$t['navAboutDeans'] = 'Dean&#39;s Message';
$t['navAboutBrief'] = 'CIS Brief';
$t['navAboutAdmission'] = 'Admission';
$t['navAboutOffice'] = 'CIS Office';
$t['navMajors'] = 'Majors';
$t['navMajorsITB'] = 'International Trade and Business';
$t['navMajorsIMC'] = 'International Marketing and Communication';
$t['navMajorsEAS'] = 'East Asian Studies';
$t['navSAPAbout'] = 'About SAP';
$t['navSAPPartners'] = 'Partner Universities';
$t['navSAPStudents'] = 'Student Testimonials';
$t['navCommunity'] = 'Community';
$t['navAdministration'] = 'Administration';
$t['navMajorsLIFS'] = 'Legal Informatics and Forensic Science';
$t['navApply'] = 'Apply';
$t['navSAP'] = 'Study Abroad Program (SAP)';
$t['footerCopyRight'] = 'College of International Studies, Hallym University';
$t['footerBackTop'] = 'Back to Top';
$t['footerAddress'] = '14110-4, International Hall, Hallym University Road 39, Chuncheon, Gangwon-do, Korea, 200-702';
$t['footerOffice'] = 'CIS Office,';
