<?php

// Generated by Transtable - 2015-04-15 20:15:40

$t['NAVBRANDMain'] = 'Hallym University';
$t['months']['1'] = 'January';
$t['form_validator_message'] = 'Enter your message';
$t['message_sent'] = 'The message is sent. Thank you for your inquiry. We will contact you soon.';
$t['facebook_icon'] = 'Join us on Facebook';
$t['page_not_found'] = 'Page not found. Visit our home page or use menu navigation on top of this page.';
$t['NAVBRANDSub'] = 'College of International Studies';
