<?php

// Generated by Transtable - 2015-04-25 17:53:23

$t['navAboutDeans'] = '딘의 메시지';
$t['navAboutFaculty'] = '학부';
$t['navBrandMain'] = '한림대학교';
$t['navAboutBrief'] = 'CIS 개요';
$t['navBrandSub'] = '국제 연구의 대학';
$t['navAbout'] = 'CIS 소개';
$t['navAboutAdmission'] = '입장';
$t['navAboutOffice'] = 'CIS 사무실';
$t['navMajors'] = '메이저';
$t['navMajorsITB'] = '국제 무역 및 비즈니스';
$t['navMajorsIMC'] = '국제 마케팅 및 커뮤니케이션';
$t['navMajorsEAS'] = '동아시아 학';
$t['navSAPAbout'] = 'SAP 소개';
$t['navSAPPartners'] = '파트너 대학';
$t['navSAPStudents'] = '학생 후기';
$t['navCommunity'] = '집단';
$t['navAdministration'] = '관리';
$t['navMajorsLIFS'] = '법률 정보학 및 법의학';
$t['navApply'] = '적용';
$t['navSAP'] = '유학 프로그램 (SAP)';
$t['footerCopyRight'] = '국제 연구 대학, 한림 대학교';
$t['footerBackTop'] = '맨 위로';
$t['footerAddress'] = '&nbsp;14110-4, 국제 홀, 한림 대학교 도로 39, 춘천, 강원도, 한국, 200-702';
$t['footerOffice'] = 'CIS 사무실을,';
