<?php

// Generated by Transtable - 2015-04-15 20:15:47

$t['page_not_found'] = 'this is some korea<br />
&nbsp;';
$t['months']['1'] = '';
$t['facebook_icon'] = 'this is some korean.';
$t['NAVBRANDMain'] = '한림대학교';
$t['NAVBRANDSub'] = '국제 연구의 대학';
